### ISSUE TITLE
Allow None as a default value for a prompt

### ISSUE THREAD

**Issue by SchoolGuy** [tmbo/questionary#133]
According to https://questionary.readthedocs.io/en/stable/pages/types.html the `default` key is there for the case that the user just hits enter, currently Questionary just exits with a `TypeError` when `default` is `None`.

Questions:
```
export_menu_questions = [
    {
        'type': 'select',
        'name': 'export_menu_target',
        'message': 'What is your desired export target?',
        'choices': [
            "String",
            "File",
            "Go back"
        ]
    },
    {
        'type': 'confirm',
        'name': 'export_menu_prettyprint_1',
        'message': 'Should the keys be sorted?',
        "when": lambda x: x["export_menu_target"] != "Go back"
    },
    {
        'type': 'text',
        'name': 'export_menu_prettyprint_2',
        'message': 'Which indentation should the keys have? (Hit enter for no indentation or enter a number)',
        'default': None,
        'validate': IntegerValidator,
        "when": lambda x: x["export_menu_target"] != "Go back"
    }
]
```

Above code has been taken from: https://github.com/cobbler/libcobblersignatures/tree/feature/pretty-print

CLI Stacktrace
```
? Should the keys be sorted? Yes
Traceback (most recent call last):
  File "/home/enno/Sources/PyCharmProjects/libcobblersignatures/venv/bin/cobbler-manage-signatures", line 11, in <module>
    load_entry_point('libcobblersignatures==0.0.1', 'console_scripts', 'cobbler-manage-signatures')()
  File "/home/enno/Sources/PyCharmProjects/libcobblersignatures/venv/lib64/python3.6/site-packages/libcobblersignatures/cli.py", line 693, in main
    export_menu()
  File "/home/enno/Sources/PyCharmProjects/libcobblersignatures/venv/lib64/python3.6/site-packages/libcobblersignatures/cli.py", line 454, in export_menu
    export_menu_answers = questionary.prompt(export_menu_questions)
  File "/home/enno/Sources/PyCharmProjects/libcobblersignatures/venv/lib64/python3.6/site-packages/questionary/prompt.py", line 68, in prompt
    return unsafe_prompt(questions, answers, patch_stdout, true_color, **kwargs)
  File "/home/enno/Sources/PyCharmProjects/libcobblersignatures/venv/lib64/python3.6/site-packages/questionary/prompt.py", line 192, in unsafe_prompt
    question = create_question_func(**_kwargs)
  File "/home/enno/Sources/PyCharmProjects/libcobblersignatures/venv/lib64/python3.6/site-packages/questionary/prompts/text.py", line 98, in text
    p.default_buffer.reset(Document(default))
  File "/home/enno/Sources/PyCharmProjects/libcobblersignatures/venv/lib64/python3.6/site-packages/prompt_toolkit/document.py", line 116, in __init__
    cursor_position = len(text)
TypeError: object of type 'NoneType' has no len()
```

**Comment by MAD-py** [comment]
I have been looking at this case and what I see is that all the questions that require a text type answer evaluate the size of the answer to know the position of the cursor.

When you look more to detail all the documentation or the code you realize that in this type of question the default value is defined as empty str and does not allow it to be None, in my opinion it is a mistake that you try to put the default value as None.

**Comment by SchoolGuy** [comment]
@MAD-py Well if that is correct then that would mean we should still document it. Because that means that we can only set non nullable str as default values and that is indeed that not a full default...

**Comment by kiancross** [comment]
`default` is an optional argument, but that doesn't necessarily mean it should accept `None`; so I don't think this is a bug.

In this case, if set, `default` takes a string. I suppose the documentation could be updated, however, I think this is implicit by the parameter being typed as `str`.

**Comment by SchoolGuy** [comment]
Hm okay, then I will close this issue. Thanks for the clarification.
