### ISSUE TITLE
Strange result

### ISSUE THREAD

**Issue by EugeneWust** [tmbo/questionary#263]
### Question

Tried this one:

```
import questionary

questionary.select(
    "What do you want to do?",
    choices=[
        'Order a pizza',
        'Make a reservation',
        'Ask for opening hours'
    ]).ask()  # returns value of selection
```

When executing this happened:

```
============ RESTART: /Users/ewust/Documents/Python Code/question.py ===========
[?2004h[?1l[?25l[0m[?7l[0m[J[0;38;5;67m?[0;1m What do you want to do? [0m(Use arrow keys)[42D[42C[?7h[0m[?25l[?7l[42D[0m[J[0;38;5;67m?[0;1m What do you want to do? [0m(Use arrow keys)[42D[0m
[J[?7h[0m[?12l[?25h[?2004lTraceback (most recent call last):
  File "/Users/ewust/Documents/Python Code/question.py", line 9, in <module>
    ]).ask()  # returns value of selection
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/questionary/question.py", line 70, in ask
    return self.unsafe_ask(patch_stdout)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/questionary/question.py", line 92, in unsafe_ask
    return self.application.run()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/prompt_toolkit/application/application.py", line 978, in run
    return loop.run_until_complete(
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 650, in run_until_complete
    return future.result()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/prompt_toolkit/application/application.py", line 885, in run_async
    return await _run_async(f)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/prompt_toolkit/application/application.py", line 750, in _run_async
    result = await f
EOFError
```

### What have you already tried?

Already switched back to Python 3.9. Same result. Working on Mac OS 12.6

Active Python at the moment:

```
Python 3.11.0 (v3.11.0:deaf509e8f, Oct 24 2022, 14:43:23) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license()" for more information.
```

Can you tell me what i am doing wrong.

Thanks in advance,

Eugène Wüst
Amsterdam

### Read the documentation

- [X] I have checked to ensure that my question is not answered by the documentation.

**Comment by kiancross** [comment]
Are you using the normal MacOS terminal? Can you try Python 3.9?

**Comment by EugeneWust** [comment]
Hi Kian,

Thanks a lot. I used the IDLE Shell with Python 3.11. Tried your suggested combination MacOS terminal and Python 3.9.15 and it worked like a charm. Thanks a lot!

Kind regards, Eugène Wüst
Amsterdam, Holland

**Comment by kiancross** [comment]
Thanks for reporting back. I've switched this to a bug for now so that I can investigate if Idle should work or not.

**Comment by kiancross** [comment]
IDLE is not supported, [as it is not a terminal emulator](https://stackoverflow.com/a/66621015).
