### ISSUE TITLE
-str' object has no attribute 'unsafe_ask' when using questionary.form

### ISSUE THREAD

**Issue by AMontagu** [tmbo/questionary#305]
### Describe the bug

When using:

```
answers = questionary.form(
    case_label=questionary.text("Enter the case label", default="My test case").ask(),
    case_number=questionary.text(
        "Enter the case number", default="000000001", validate=CaseNumberValidator
    ).ask(),
    manager_email=questionary.text("Enter the manager email", default="My test case")
    .skip_if(manager_email is not None, default=manager_email)
    .ask(),
    offer_item_code=questionary.select(
        "Choose the atlas code for the LV. They are filtered by project name.",
        choices=self.get_offer_item_code_by_app(project_name),
    ),
).ask()
```

it raise: 
```
Traceback (most recent call last):
  File "./manage.py", line 21, in <module>
    main()
  File "./manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/code/atlas/management/commands/debuggablecommand.py", line 22, in execute
    return super().execute(*args, **options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
  File "/opt/code/atlas/management/commands/import_for_dev.py", line 103, in handle
    self.create_data_from_user_input(options["project_name"], options["user_email"])
  File "/opt/code/atlas/management/commands/import_for_dev.py", line 122, in create_data_from_user_input
    answers = questionary.form(
  File "/usr/local/lib/python3.8/site-packages/questionary/form.py", line 94, in ask
    return self.unsafe_ask(patch_stdout)
  File "/usr/local/lib/python3.8/site-packages/questionary/form.py", line 60, in unsafe_ask
    return {f.key: f.question.unsafe_ask(patch_stdout) for f in self.form_fields}
  File "/usr/local/lib/python3.8/site-packages/questionary/form.py", line 60, in <dictcomp>
    return {f.key: f.question.unsafe_ask(patch_stdout) for f in self.form_fields}
AttributeError: 'str' object has no attribute 'unsafe_ask
```

### Example

```python
answers = questionary.form(
    case_label=questionary.text("Enter the case label", default="My test case").ask(),
    case_number=questionary.text(
        "Enter the case number", default="000000001", validate=CaseNumberValidator
    ).ask(),
    manager_email=questionary.text("Enter the manager email", default="My test case")
    .skip_if(manager_email is not None, default=manager_email)
    .ask(),
    offer_item_code=questionary.select(
        "Choose the atlas code for the LV. They are filtered by project name.",
        choices=self.get_offer_item_code_by_app(project_name),
    ),
).ask()
```

### Expected behaviour

form working correctly

### Latest version

- [X] I have checked that this issue occurs on the latest version of questionary.

### Questionary version

2.0.0

### Prompt Toolkit version

3.0.36

### Operating System

Linux

**Comment by kiancross** [comment]
You should only call `.ask` on the form. e.g.,

```python
    case_label=questionary.text("Enter the case label", default="My test case").ask(),
```
should be
```
    case_label=questionary.text("Enter the case label", default="My test case"),
```

Change all the others, then it should work.
