### ISSUE TITLE
unable to run examples / causing exceptions

### ISSUE THREAD

**Issue by xmatthias** [tmbo/questionary#36]
I seem to be unable to run any of the examples.

I don't think it's related to my environment - i'm using a brand-new 3.8.0 Virtual environment, created for this sole purpose.

Installation steps:

```
git clone https://github.com/tmbo/questionary
cd questionary
# Below is identical to pip install -e .
python setup.py develop 

python examples/confirm.py
```

environment:
``` bash 
$ pip freeze
prompt-toolkit==3.0.3
-e git+git@github.com:tmbo/questionary.git@e66adfcc1d2b56e8d8d559a4e1bf9dcff23eb3b7#egg=questionary
wcwidth==0.1.8
```

Error received:
``` 
# Same happens with other examples, too
$python examples/confirm.py

Traceback (most recent call last):
  File "examples/confirm.py", line 7, in <module>
    import questionary
  File "/home/matt/github/questionary/questionary/__init__.py", line 2, in <module>
    from prompt_toolkit.validation import Validator, ValidationError
  File "/home/matt/.pyenv/versions/questionary/lib/python3.8/site-packages/prompt_toolkit-3.0.3-py3.8.egg/prompt_toolkit/__init__.py", line 16, in <module>
    from .application import Application
  File "/home/matt/.pyenv/versions/questionary/lib/python3.8/site-packages/prompt_toolkit-3.0.3-py3.8.egg/prompt_toolkit/application/__init__.py", line 1, in <module>
    from .application import Application
  File "/home/matt/.pyenv/versions/questionary/lib/python3.8/site-packages/prompt_toolkit-3.0.3-py3.8.egg/prompt_toolkit/application/application.py", line 1, in <module>
    import asyncio
  File "/home/matt/.pyenv/versions/3.8.0/lib/python3.8/asyncio/__init__.py", line 8, in <module>
    from .base_events import *
  File "/home/matt/.pyenv/versions/3.8.0/lib/python3.8/asyncio/base_events.py", line 23, in <module>
    import socket
  File "/home/matt/.pyenv/versions/3.8.0/lib/python3.8/socket.py", line 52, in <module>
    import os, sys, io, selectors
  File "/home/matt/.pyenv/versions/3.8.0/lib/python3.8/selectors.py", line 12, in <module>
    import select
  File "/home/matt/github/questionary/examples/select.py", line 9, in <module>
    from questionary import Separator, Choice, prompt
  File "/home/matt/github/questionary/questionary/prompt.py", line 3, in <module>
    from prompt_toolkit.output import ColorDepth
  File "/home/matt/.pyenv/versions/questionary/lib/python3.8/site-packages/prompt_toolkit-3.0.3-py3.8.egg/prompt_toolkit/output/__init__.py", line 3, in <module>
    from .defaults import create_output
  File "/home/matt/.pyenv/versions/questionary/lib/python3.8/site-packages/prompt_toolkit-3.0.3-py3.8.egg/prompt_toolkit/output/defaults.py", line 4, in <module>
    from prompt_toolkit.patch_stdout import StdoutProxy
  File "/home/matt/.pyenv/versions/questionary/lib/python3.8/site-packages/prompt_toolkit-3.0.3-py3.8.egg/prompt_toolkit/patch_stdout.py", line 22, in <module>
    from asyncio import get_event_loop
ImportError: cannot import name 'get_event_loop' from partially initialized module 'asyncio' (most likely due to a circular import) (/home/matt/.pyenv/versions/3.8.0/lib/python3.8/asyncio/__init__.py)
```

I'm not certain what is causing this, as running a python shell and importing questionary there does work - and also running it from within the project I've integrated questionary it works fine (however i import only the prompt in that case).

Strangely, it works when running the scripts as module

```
python -m examples.confirm
```

**Comment by tmbo** [comment]
this is an import issue due to one of the examples being named `select`, it gets resolved wrongly...
```
 File "/home/matt/.pyenv/versions/3.8.0/lib/python3.8/selectors.py", line 12, in <module>
    import select
  File "/home/matt/github/questionary/examples/select.py", line 9, in <module>
```

**Comment by xmatthias** [comment]
great catch - sorry for not spotting this!
